USE sakila;
SHOW tables;

-- 1. List the number of films per category.
SELECT c.name, COUNT(f.film_id) AS film_count
FROM category AS c
JOIN film_category AS f ON c.category_id = f.category_id
GROUP BY c.name
ORDER BY film_count DESC;

-- 2. Retrieve the store ID, city, and country for each store.
SELECT s.store_id, c.city, co.country
FROM store AS s
JOIN address AS a ON s.address_id=a.address_id
JOIN city AS c ON a.city_id=c.city_id
JOIN country AS co ON c.country_id=co.country_id; 

-- 3. Calculate the total revenue generated by each store in dollars.
SELECT st.store_id, SUM(p.amount) AS total_revenue
FROM store AS st
JOIN staff AS s ON st.store_id=s.store_id
JOIN payment AS p ON s.staff_id=p.staff_id
GROUP BY st.store_id
ORDER BY total_revenue DESC; 

-- 4. Determine the average running time of films for each category.film
SELECT c.name, AVG(f.length) AS running_time
FROM film_category AS fc
JOIN category AS c ON fc.category_id=c.category_id
JOIN film AS f ON fc.film_id=f.film_id
GROUP BY c.name
ORDER BY running_time ASC; 